const userRows = [
    { id: 1,
        firstName: 'Mohamed',
        age: 35 ,
        status:'active' ,
        transaction:"$120" ,
        email:"moh@gmail.com" ,
        Remove : "Remove",
        edit : 'edit'
       },
       { id: 2,
          firstName: 'ahmed',
          age: 35 ,
          status:'active' ,
          transaction:"$100" ,
          email:"Ahm@gmail.com" ,
          Remove : "Remove",
          edit : 'edit'
         },
         { id: 3,
          firstName: 'Ali',
          age: 35 ,
          status:'active' ,
          transaction:"$120" ,
          email:"Ali@gmail.com" ,
          Remove : "Remove",
          edit : 'edit'
         },
         { id: 4,
          firstName: 'ramdan',
          age: 35 ,
          status:'active' ,
          transaction:"$940" ,
          email:"Rmo@gmail.com" ,
          Remove : "Remove",
          edit : 'edit'
         },
         { id: 5,
          firstName: 'samy',
          age: 35 ,
          status:'active' ,
          transaction:"$400" ,
          email:"Sbd@gmail.com" ,
          Remove : "Remove",
          edit : 'edit'
         },
         { id: 6,
          firstName: 'Mohamed',
          age: 35 ,
          status:'active' ,
          transaction:"$120" ,
          email:"Mo@gmail.com" ,
          Remove : "Remove",
          edit : 'edit'
         },
         { id: 7,
          firstName: 'hossam',
          age: 15 ,
          status:'active' ,
          transaction:"$740" ,
          email:"hos@gmail.com" ,
          Remove : "Remove",
          edit : 'edit'
         },
         { id: 8,
          firstName: 'sayed',
          age: 20 ,
          status:'active' ,
          transaction:"$120" ,
          email:"day@gmail.com" ,
          Remove : "Remove",
          edit : 'edit'
         },
         { id: 9,
          firstName: 'hossam',
          age: 15 ,
          status:'active' ,
          transaction:"$740" ,
          email:"hos@gmail.com" ,
          Remove : "Remove",
          edit : 'edit'
         },
         { id: 10,
          firstName: 'sayed',
          age: 20 ,
          status:'active' ,
          transaction:"$120" ,
          email:"day@gmail.com" ,
          Remove : "Remove",
          edit : 'edit'
         },
  
  ];
  export default userRows